name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (CPU tag)
        run: docker build -t sufiyanhub/crime-prediction-img:cpu .

      - name: Push Docker image (CPU tag)
        run: docker push sufiyanhub/crime-prediction-img:cpu
